// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHk8xYPlMRgOBnuvpT3l9VAcrgg1zlmHs',
    appId: '1:418761399439:web:dc0aac0c47221ba644e4fa',
    messagingSenderId: '418761399439',
    projectId: 'projeto-brassket',
    authDomain: 'projeto-brassket.firebaseapp.com',
    storageBucket: 'projeto-brassket.firebasestorage.app',
    measurementId: 'G-K9RJEYR4Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz9-H3V0g81GQ7emAsZ1AU5YRWeNjLVFg',
    appId: '1:418761399439:android:92fb1bd5cb11e12044e4fa',
    messagingSenderId: '418761399439',
    projectId: 'projeto-brassket',
    storageBucket: 'projeto-brassket.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAB--CZFEu7drCz6HQkkkUrz6H0UI3oz0',
    appId: '1:418761399439:ios:7e8b588b6c9b153644e4fa',
    messagingSenderId: '418761399439',
    projectId: 'projeto-brassket',
    storageBucket: 'projeto-brassket.firebasestorage.app',
    iosBundleId: 'com.example.projetoBrassket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAB--CZFEu7drCz6HQkkkUrz6H0UI3oz0',
    appId: '1:418761399439:ios:7e8b588b6c9b153644e4fa',
    messagingSenderId: '418761399439',
    projectId: 'projeto-brassket',
    storageBucket: 'projeto-brassket.firebasestorage.app',
    iosBundleId: 'com.example.projetoBrassket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHk8xYPlMRgOBnuvpT3l9VAcrgg1zlmHs',
    appId: '1:418761399439:web:2c0503d06f0f154344e4fa',
    messagingSenderId: '418761399439',
    projectId: 'projeto-brassket',
    authDomain: 'projeto-brassket.firebaseapp.com',
    storageBucket: 'projeto-brassket.firebasestorage.app',
    measurementId: 'G-FWHMQ4N6G7',
  );
}
